name: change_cookie_CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  install_components:
    runs-on: ubuntu-latest

    steps:
    - name: Check Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'

    - name: install packags
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m playwright
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

  run_playwright_tests:
    runs-on: ubuntu-latest
    needs: install_components

    steps:
    - name: install browsers
      run:
        python -m playwright install

    - name: run test in 3 browsers
      run:
        python -m pytest --html=report.html --self-contained-html --browser chromium --browser firefox --browser webkit -n auto

      