name: change_cookie_CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  install_components:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: install packags
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pytest-playwright
        python -m playwright install
        python -m pip install pytest-xdist
        python -m pip install pytest-html

    - name: Check if venv exists
      run: |
        ls -la venv/bin/


  run_playwright_tests:
    runs-on: ubuntu-22.04
    needs: install_components

    steps:
    - name: Make virtual env
      run: |
        python -m venv venv
        source venv/bin/activate
        ls -la venv/bin/
        
    - name: packages list
      run: |
        source venv/bin/activate
        python -m pip list

    - name: run test in 3 browsers
      run: |
        python -m pip install pytest
        python -m pip install pytest-playwright
        python -m pip install pytest-xdist
        python -m pip install pytest-html
        python -m pytest tests/ --browser chromium --browser firefox --browser webkit -n auto